
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/semana3
    username: root
    password: 1289
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
